// Imperators information array //
let emperors = [
    {
        emperorName: "Augustus",
        emperorFrom: -27,
        emperorUntil: 14,
        Born: -60,
        originCity: "Rome",
        originProvince: "Italy",
        causeOfDeath: "natural",
        emperorImages: [
            'images/emperors/augustus-bust.jpg',
            'images/emperors/augustus-statue.jpg',
            'images/emperors/augustus-voshart.jpg',
        ],
        emperorDescription: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorum repellat molestias, numquam quos suscipit, quo tempore, omnis blanditiis dolores expedita ullam aperiam fugiat. Dolores, eos ad eaque quia nisi sunt?",
    },
    {
        emperorName: "Tiberius",
        emperorFrom: 14,
        emperorUntil: 37,
        Born: -40,
        originCity: "Rome",
        originProvince: "Italy",
        causeOfDeath: "chokedPillow",
        emperorImages: [
            'images/emperors/tiberius-bust.jpg',
            'images/emperors/tiberius-statue.jpg',
            'images/emperors/tiberius-voshart.jpg',
        ],
        emperorDescription: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorum repellat molestias, numquam quos suscipit, quo tempore, omnis blanditiis dolores expedita ullam aperiam fugiat. Dolores, eos ad eaque quia nisi sunt?",
   
    },
    {
        emperorName: "Caligula",
        emperorFrom: 37,
        emperorUntil: 41,
        Born: 12,
        originCity: "Rome",
        originProvince: "Italy",
        causeOfDeath: "byTheSword",
        emperorImages: [
            'images/emperors/caligula-bust.jpg',
            'images/emperors/caligula-statue.jpg',
            'images/emperors/caligula-voshart.jpg',
        ],
        emperorDescription: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorum repellat molestias, numquam quos suscipit, quo tempore, omnis blanditiis dolores expedita ullam aperiam fugiat. Dolores, eos ad eaque quia nisi sunt?",
   
    },
    {
        emperorName: "Claudius",
        emperorFrom: 41,
        emperorUntil: 54,
        Born: -10,
        originCity: "Lugdunum (Lyon)",
        originProvince: "Galia",
        causeOfDeath: "poisoned",
        emperorImages: [
            'images/emperors/claudius-bust.jpg',
            'images/emperors/claudius-statue.jpg',
            'images/emperors/claudius-voshart.jpg',
        ],
        emperorDescription: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorum repellat molestias, numquam quos suscipit, quo tempore, omnis blanditiis dolores expedita ullam aperiam fugiat. Dolores, eos ad eaque quia nisi sunt?",
   
    },
    {
        emperorName: "Nero",
        emperorFrom: 68,
        emperorUntil: 69,
        Born: -3,
        originCity: "Terracina",
        originProvince: "Italy",
        causeOfDeath: "suicide",
        emperorImages: [
            'images/emperors/nero-bust.jpg',
            'images/emperors/nero-statue.jpg',
            'images/emperors/nero-voshart.jpg',
        ],
        emperorDescription: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorum repellat molestias, numquam quos suscipit, quo tempore, omnis blanditiis dolores expedita ullam aperiam fugiat. Dolores, eos ad eaque quia nisi sunt?",
    },
    {
        emperorName: "Galba",
        emperorFrom: 69,
        emperorUntil: 69,
        Born: 37,
        originCity: "Rome",
        originProvince: "Italy",
        causeOfDeath: "byTheSword",
        emperorImages: [
            'images/emperors/galba-bust.jpg',
            'images/emperors/galba-statue.jpg',
            'images/emperors/galba-voshart.jpg',
        ],
        emperorDescription: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorum repellat molestias, numquam quos suscipit, quo tempore, omnis blanditiis dolores expedita ullam aperiam fugiat. Dolores, eos ad eaque quia nisi sunt?",
    },
    {
        emperorName: "Otho",
        emperorFrom: 69,
        emperorUntil: 69,
        Born: 32,
        originCity: "Ferentium",
        originProvince: "Italy",
        causeOfDeath: "suicide",
        emperorImages: [
            'images/emperors/otho-bust.jpg',
            'images/emperors/otho-statue.jpg',
            'images/emperors/otho-voshart.jpg',
        ],
        emperorDescription: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorum repellat molestias, numquam quos suscipit, quo tempore, omnis blanditiis dolores expedita ullam aperiam fugiat. Dolores, eos ad eaque quia nisi sunt?",
    },
    {
        emperorName: "Vitellius",
        emperorFrom: 69,
        emperorUntil: 69,
        Born: 15,
        originCity: "Rome",
        originProvince: "Italy",
        causeOfDeath: "byTheSword",
        emperorImages: [
            'images/emperors/vitellius-bust.jpg',
            'images/emperors/vitellius-painting.jpg',
            'images/emperors/vitellius-voshart.jpg',
        ],
        emperorDescription: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorum repellat molestias, numquam quos suscipit, quo tempore, omnis blanditiis dolores expedita ullam aperiam fugiat. Dolores, eos ad eaque quia nisi sunt?",
    },
    {
        emperorName: "Vespasianus",
        emperorFrom: 69,
        emperorUntil: 79,
        Born: 9,
        originCity: "Falacrina",
        originProvince: "Italy",
        causeOfDeath: "natural",
        emperorImages: [
            'images/emperors/vespasianus-bust.jpg',
            'images/emperors/vespasianus-bust2.jpg',
            'images/emperors/vespasianus-voshart.jpg',
        ],
        emperorDescription: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorum repellat molestias, numquam quos suscipit, quo tempore, omnis blanditiis dolores expedita ullam aperiam fugiat. Dolores, eos ad eaque quia nisi sunt?",
    },
    {
        emperorName: "Titus",
        emperorFrom: 79,
        emperorUntil: 81,
        Born: 39,
        originCity: "Rome",
        originProvince: "Italy",
        causeOfDeath: "natural",
        emperorImages: [
            'images/emperors/titus-bust.jpg',
            'images/emperors/titus-statue.jpg',
            'images/emperors/titus-voshart.jpg',
        ],
        emperorDescription: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorum repellat molestias, numquam quos suscipit, quo tempore, omnis blanditiis dolores expedita ullam aperiam fugiat. Dolores, eos ad eaque quia nisi sunt?",
    },
    {
        emperorName: "Domitianus",
        emperorFrom: 81,
        emperorUntil: 96,
        Born: 51,
        originCity: "Rome",
        originProvince: "Italy",
        causeOfDeath: "byTheSword",
        emperorImages: [
            'images/emperors/domitianus-bust.jpg',
            'images/emperors/domitianus-statue.jpg',
            'images/emperors/domitianus-voshart.jpg',
        ],
        emperorDescription: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorum repellat molestias, numquam quos suscipit, quo tempore, omnis blanditiis dolores expedita ullam aperiam fugiat. Dolores, eos ad eaque quia nisi sunt?",
    },
    {
        emperorName: "Nerva",
        emperorFrom: 96,
        emperorUntil: 98,
        Born: 30,
        originCity: "Narni",
        originProvince: "Italy",
        causeOfDeath: "natural",
        emperorImages: [
            'images/emperors/nerva-bust.jpg',
            'images/emperors/nerva-statue.jpg',
            'images/emperors/nerva-voshart.jpg',
        ],
        emperorDescription: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorum repellat molestias, numquam quos suscipit, quo tempore, omnis blanditiis dolores expedita ullam aperiam fugiat. Dolores, eos ad eaque quia nisi sunt?",
    },
    {
        emperorName: "Traianus",
        emperorFrom: 98,
        emperorUntil: 117,
        Born: 53,
        originCity: "Italica",
        originProvince: "Hispania",
        causeOfDeath: "natural",
        emperorImages: [
            'images/emperors/traianus-bust.jpg',
            'images/emperors/traianus-statue.jpg',
            'images/emperors/traianus-voshart.jpg',
        ],
        emperorDescription: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorum repellat molestias, numquam quos suscipit, quo tempore, omnis blanditiis dolores expedita ullam aperiam fugiat. Dolores, eos ad eaque quia nisi sunt?",
    },
    {
        emperorName: "Hadrianus",
        emperorFrom: 117,
        emperorUntil: 138,
        Born: 76,
        originCity: "Italica",
        originProvince: "Hispania",
        causeOfDeath: "natural",
        emperorImages: [
            'images/emperors/hadrianus-bust.jpg',
            'images/emperors/hadrianus-statue.jpg',
            'images/emperors/hadrianus-voshart.jpg',
        ],
        emperorDescription: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorum repellat molestias, numquam quos suscipit, quo tempore, omnis blanditiis dolores expedita ullam aperiam fugiat. Dolores, eos ad eaque quia nisi sunt?",
    },
    {
        emperorName: "Antoninus Pius",
        emperorFrom: 138,
        emperorUntil: 161,
        Born: 86,
        originCity: "Lanuvium",
        originProvince: "Italy",
        causeOfDeath: "natural",
        emperorImages: [
            'images/emperors/antoninus-bust.jpg',
            'images/emperors/antoninus-statue.jpg',
            'images/emperors/antoninus-voshart.jpg',
        ],
        emperorDescription: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorum repellat molestias, numquam quos suscipit, quo tempore, omnis blanditiis dolores expedita ullam aperiam fugiat. Dolores, eos ad eaque quia nisi sunt?",
    },
    {
        emperorName: "Marcus Aurelius",
        emperorFrom: 161,
        emperorUntil: 180,
        Born: 121,
        originCity: "Rome",
        originProvince: "Italy",
        causeOfDeath: "natural",
        emperorImages: [
            'images/emperors/marcusAurelius-bust.jpg',
            'images/emperors/marcusAurelius-statue.jpg',
            'images/emperors/marcusAurelius-voshart.jpg',
        ],
        emperorDescription: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorum repellat molestias, numquam quos suscipit, quo tempore, omnis blanditiis dolores expedita ullam aperiam fugiat. Dolores, eos ad eaque quia nisi sunt?",
    },
        {
        emperorName: "Lucius Verus",
        emperorFrom: 161,
        emperorUntil: 169,
        Born: 130,
        originCity: "Altinum",
        originProvince: "Italy",
        causeOfDeath: "natural",
        emperorImages: [
            'images/emperors/luciusVerus-bust.jpg',
            'images/emperors/luciusVerus-statue.jpg',
            'images/emperors/luciusVerus-voshart.jpg',
        ],
        emperorDescription: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorum repellat molestias, numquam quos suscipit, quo tempore, omnis blanditiis dolores expedita ullam aperiam fugiat. Dolores, eos ad eaque quia nisi sunt?",
    },
    {
        emperorName: "Commodus",
        emperorFrom: 177,
        emperorUntil: 192,
        Born: 161,
        originCity: "Lanuvium",
        originProvince: "Italy",
        causeOfDeath: "byTheSword",
        emperorImages: [
            'images/emperors/commodus-bust.jpg',
            'images/emperors/commodus-statue.jpg',
            'images/emperors/commodus-voshart.jpg',
        ],
        emperorDescription: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorum repellat molestias, numquam quos suscipit, quo tempore, omnis blanditiis dolores expedita ullam aperiam fugiat. Dolores, eos ad eaque quia nisi sunt?",
    },
]